import type { LangCode } from "./i18n";

type MapCopy = Record<
  | "text"
  | "map"
  | "satellite"
  | "issued"
  | "valid"
  | "current"
  | "expired"
  | "unavailable"
  | "guide"
  | "fit"
  | "offline"
  | "points"
  | "tiles"
  | "sector"
  | "autoSector"
  | "allSectors"
  | "coverageGap"
  | "authority",
  string
>;

export const mapCopy: Record<LangCode, MapCopy> = {
  "en": {
    "text": "Text only",
    "map": "Map",
    "satellite": "Satellite",
    "issued": "Issued",
    "valid": "Valid until",
    "current": "Current advisory",
    "expired": "Advisory expired",
    "unavailable": "No current PFZ advisory available",
    "guide": "How to read this map",
    "fit": "Show advisory points",
    "offline": "Offline — no new updates",
    "points": "Advisory points",
    "tiles": "Map imagery could not load. Use Text only.",
    "sector": "Coastal Sector",
    "autoSector": "From selected location",
    "allSectors": "All sectors",
    "coverageGap": "Coverage unavailable — issuance not verified",
    "authority": "Authority",
  },
  "hi": {
    "text": "केवल पाठ",
    "map": "मानचित्र",
    "satellite": "उपग्रह",
    "issued": "जारी",
    "valid": "तक मान्य",
    "current": "वर्तमान परामर्श",
    "expired": "परामर्श समाप्त",
    "unavailable": "वर्तमान PFZ परामर्श उपलब्ध नहीं",
    "guide": "यह मानचित्र कैसे पढ़ें",
    "fit": "परामर्श बिंदु दिखाएँ",
    "offline": "ऑफ़लाइन — नए अपडेट नहीं",
    "points": "परामर्श बिंदु",
    "tiles": "मानचित्र लोड नहीं हुआ। केवल पाठ चुनें।",
    "sector": "तटीय क्षेत्र",
    "autoSector": "चुने हुए स्थान से",
    "allSectors": "सभी क्षेत्र",
    "coverageGap": "कवरेज उपलब्ध नहीं — परामर्श जारी होने की पुष्टि नहीं",
    "authority": "प्राधिकरण",
  },
  "gu": {
    "text": "માત્ર લખાણ",
    "map": "નકશો",
    "satellite": "ઉપગ્રહ",
    "issued": "જારી",
    "valid": "સુધી માન્ય",
    "current": "વર્તમાન સલાહ",
    "expired": "સલાહની મુદત પૂરી",
    "unavailable": "વર્તમાન PFZ સલાહ ઉપલબ્ધ નથી",
    "guide": "આ નકશો કેવી રીતે વાંચવો",
    "fit": "સલાહના બિંદુઓ બતાવો",
    "offline": "ઓફલાઇન — નવા અપડેટ નથી",
    "points": "સલાહના બિંદુઓ",
    "tiles": "નકશો લોડ થયો નથી. માત્ર લખાણ પસંદ કરો.",
    "sector": "દરિયાકાંઠાનો વિસ્તાર",
    "autoSector": "પસંદ કરેલા સ્થાન પરથી",
    "allSectors": "બધા સેક્ટર",
    "coverageGap": "કવરેજ ઉપલબ્ધ નથી — સલાહ જારી થયાની પુષ્ટિ નથી",
    "authority": "સત્તામંડળ",
  },
  "mr": {
    "text": "फक्त मजकूर",
    "map": "नकाशा",
    "satellite": "उपग्रह",
    "issued": "जारी",
    "valid": "पर्यंत वैध",
    "current": "सध्याचा सल्ला",
    "expired": "सल्ल्याची मुदत संपली",
    "unavailable": "सध्याचा PFZ सल्ला उपलब्ध नाही",
    "guide": "हा नकाशा कसा वाचावा",
    "fit": "सल्ल्याचे बिंदू दाखवा",
    "offline": "ऑफलाइन — नवीन अपडेट नाहीत",
    "points": "सल्ल्याचे बिंदू",
    "tiles": "नकाशा लोड झाला नाही. फक्त मजकूर निवडा.",
    "sector": "किनारपट्टी क्षेत्र",
    "autoSector": "निवडलेल्या स्थानावरून",
    "allSectors": "सर्व क्षेत्रे",
    "coverageGap": "कव्हरेज उपलब्ध नाही — सल्ला जारी झाल्याची पुष्टी नाही",
    "authority": "प्राधिकरण",
  },
  "ta": {
    "text": "உரை மட்டும்",
    "map": "வரைபடம்",
    "satellite": "செயற்கைக்கோள்",
    "issued": "வெளியீடு",
    "valid": "செல்லுபடியாகும் வரை",
    "current": "தற்போதைய அறிவுரை",
    "expired": "அறிவுரை காலாவதியானது",
    "unavailable": "தற்போதைய PFZ அறிவுரை இல்லை",
    "guide": "வரைபடத்தைப் படிப்பது எப்படி",
    "fit": "அறிவுரை இடங்களைக் காட்டு",
    "offline": "இணையமில்லை — புதிய தகவல்கள் இல்லை",
    "points": "அறிவுரை இடங்கள்",
    "tiles": "வரைபடம் ஏறவில்லை. உரை மட்டும் தேர்ந்தெடுக்கவும்.",
    "sector": "கடலோர மண்டலம்",
    "autoSector": "தேர்ந்தெடுத்த இடத்திலிருந்து",
    "allSectors": "அனைத்து மண்டலங்களும்",
    "coverageGap": "தகவல் கிடைக்கவில்லை — அறிவுரை வெளியீடு உறுதிப்படுத்தப்படவில்லை",
    "authority": "அதிகாரம்",
  },
  "te": {
    "text": "వచనం మాత్రమే",
    "map": "పటం",
    "satellite": "ఉపగ్రహం",
    "issued": "జారీ",
    "valid": "వరకు చెల్లుతుంది",
    "current": "ప్రస్తుత సలహా",
    "expired": "సలహా గడువు ముగిసింది",
    "unavailable": "ప్రస్తుత PFZ సలహా అందుబాటులో లేదు",
    "guide": "ఈ పటాన్ని ఎలా చదవాలి",
    "fit": "సలహా ప్రదేశాలు చూపు",
    "offline": "ఆఫ్‌లైన్ — కొత్త సమాచారం లేదు",
    "points": "సలహా ప్రదేశాలు",
    "tiles": "పటం లోడ్ కాలేదు. వచనం మాత్రమే ఎంచుకోండి.",
    "sector": "తీర ప్రాంతం",
    "autoSector": "ఎంచుకున్న స్థానం నుండి",
    "allSectors": "అన్ని రంగాలు",
    "coverageGap": "సమాచారం అందుబాటులో లేదు — సలహా జారీ నిర్ధారించబడలేదు",
    "authority": "అథారిటీ",
  },
  "ml": {
    "text": "വാചകം മാത്രം",
    "map": "ഭൂപടം",
    "satellite": "ഉപഗ്രഹം",
    "issued": "പുറപ്പെടുവിച്ചത്",
    "valid": "സാധുത അവസാനിക്കുന്നത്",
    "current": "നിലവിലെ നിർദേശം",
    "expired": "നിർദേശം കാലഹരണപ്പെട്ടു",
    "unavailable": "നിലവിലെ PFZ നിർദേശം ലഭ്യമല്ല",
    "guide": "ഈ ഭൂപടം വായിക്കുന്ന വിധം",
    "fit": "നിർദേശ സ്ഥലങ്ങൾ കാണിക്കുക",
    "offline": "ഓഫ്‌ലൈൻ — പുതിയ വിവരങ്ങളില്ല",
    "points": "നിർദേശ സ്ഥലങ്ങൾ",
    "tiles": "ഭൂപടം ലഭ്യമല്ല. വാചകം മാത്രം തിരഞ്ഞെടുക്കുക.",
    "sector": "തീരദേശ മേഖല",
    "autoSector": "തിരഞ്ഞെടുത്ത സ്ഥലത്തിൽ നിന്ന്",
    "allSectors": "എല്ലാ മേഖലകളും",
    "coverageGap": "വിവരം ലഭ്യമല്ല — നിർദേശം നൽകിയതായി സ്ഥിരീകരിച്ചിട്ടില്ല",
    "authority": "അധികാര കേന്ദ്രം",
  },
  "bn": {
    "text": "শুধু লেখা",
    "map": "মানচিত্র",
    "satellite": "উপগ্রহ",
    "issued": "প্রকাশিত",
    "valid": "পর্যন্ত বৈধ",
    "current": "বর্তমান পরামর্শ",
    "expired": "পরামর্শের মেয়াদ শেষ",
    "unavailable": "বর্তমান PFZ পরামর্শ উপলব্ধ নয়",
    "guide": "এই মানচিত্র কীভাবে পড়বেন",
    "fit": "পরামর্শের স্থান দেখান",
    "offline": "অফলাইন — নতুন তথ্য নেই",
    "points": "পরামর্শের স্থান",
    "tiles": "মানচিত্র লোড হয়নি। শুধু লেখা বেছে নিন।",
    "sector": "উপকূলীয় অঞ্চল",
    "autoSector": "নির্বাচিত অবস্থান থেকে",
    "allSectors": "সকল অঞ্চল",
    "coverageGap": "তথ্য অনুপলব্ধ — পরামর্শ জারির নিশ্চয়তা নেই",
    "authority": "কর্তৃপক্ষ",
  },
  "kn": {
    "text": "ಪಠ್ಯ ಮಾತ್ರ",
    "map": "ನಕ್ಷೆ",
    "satellite": "ಉಪಗ್ರಹ",
    "issued": "ಬಿಡುಗಡೆ",
    "valid": "ವರೆಗೆ ಮಾನ್ಯ",
    "current": "ಪ್ರಸ್ತುತ ಸಲಹೆ",
    "expired": "ಸಲಹೆಯ ಅವಧಿ ಮುಗಿದಿದೆ",
    "unavailable": "ಪ್ರಸ್ತುತ PFZ ಸಲಹೆ ಲಭ್ಯವಿಲ್ಲ",
    "guide": "ಈ ನಕ್ಷೆ ಓದುವುದು ಹೇಗೆ",
    "fit": "ಸಲಹೆಯ ಸ್ಥಳಗಳನ್ನು ತೋರಿಸಿ",
    "offline": "ಆಫ್‌ಲೈನ್ — ಹೊಸ ಮಾಹಿತಿ ಇಲ್ಲ",
    "points": "ಸಲಹೆಯ ಸ್ಥಳಗಳು",
    "tiles": "ನಕ್ಷೆ ಲೋಡ್ ಆಗಿಲ್ಲ. ಪಠ್ಯ ಮಾತ್ರ ಆಯ್ಕೆಮಾಡಿ.",
    "sector": "ಕರಾವಳಿ ವಲಯ",
    "autoSector": "ಆಯ್ಕೆಮಾಡಿದ ಸ್ಥಳದಿಂದ",
    "allSectors": "ಎಲ್ಲಾ ವಲಯಗಳು",
    "coverageGap": "ಮಾಹಿತಿ ಲಭ್ಯವಿಲ್ಲ — ಸಲಹೆ ಬಿಡುಗಡೆಯ ದೃಢೀಕರಣ ಇಲ್ಲ",
    "authority": "ಪ್ರಾಧಿಕಾರ",
  },
  "or": {
    "text": "କେବଳ ପାଠ୍ୟ",
    "map": "ମାନଚିତ୍ର",
    "satellite": "ଉପଗ୍ରହ",
    "issued": "ଜାରି",
    "valid": "ପର୍ଯ୍ୟନ୍ତ ବୈଧ",
    "current": "ବର୍ତ୍ତମାନର ପରାମର୍ଶ",
    "expired": "ପରାମର୍ଶର ସମୟ ସରିଛି",
    "unavailable": "ବର୍ତ୍ତମାନ PFZ ପରାମର୍ଶ ଉପଲବ୍ଧ ନାହିଁ",
    "guide": "ଏହି ମାନଚିତ୍ର କିପରି ପଢ଼ିବେ",
    "fit": "ପରାମର୍ଶ ସ୍ଥାନ ଦେଖାନ୍ତୁ",
    "offline": "ଅଫଲାଇନ — ନୂଆ ସୂଚନା ନାହିଁ",
    "points": "ପରାମର୍ଶ ସ୍ଥାନ",
    "tiles": "ମାନଚିତ୍ର ଲୋଡ୍ ହୋଇନି। କେବଳ ପାଠ୍ୟ ବାଛନ୍ତୁ।",
    "sector": "ଉପକୂଳ କ୍ଷେତ୍ର",
    "autoSector": "ବାଛିଥିବା ସ୍ଥାନରୁ",
    "allSectors": "ସମସ୍ତ କ୍ଷେତ୍ର",
    "coverageGap": "ତଥ୍ୟ ଉପଲବ୍ଧ ନାହିଁ — ପରାମର୍ଶ ଜାରି ନିଶ୍ଚିତ ହୋଇନାହିଁ",
    "authority": "ପ୍ରାଧିକରଣ",
  },
  "pa": {
    "text": "ਸਿਰਫ਼ ਲਿਖਤ",
    "map": "ਨਕਸ਼ਾ",
    "satellite": "ਉਪਗ੍ਰਹਿ",
    "issued": "ਜਾਰੀ",
    "valid": "ਤੱਕ ਵੈਧ",
    "current": "ਮੌਜੂਦਾ ਸਲਾਹ",
    "expired": "ਸਲਾਹ ਦੀ ਮਿਆਦ ਮੁੱਕੀ",
    "unavailable": "ਮੌਜੂਦਾ PFZ ਸਲਾਹ ਉਪਲਬਧ ਨਹੀਂ",
    "guide": "ਇਹ ਨਕਸ਼ਾ ਕਿਵੇਂ ਪੜ੍ਹਨਾ ਹੈ",
    "fit": "ਸਲਾਹ ਦੇ ਸਥਾਨ ਦਿਖਾਓ",
    "offline": "ਆਫ਼ਲਾਈਨ — ਨਵੀਂ ਜਾਣਕਾਰੀ ਨਹੀਂ",
    "points": "ਸਲਾਹ ਦੇ ਸਥਾਨ",
    "tiles": "ਨਕਸ਼ਾ ਲੋਡ ਨਹੀਂ ਹੋਇਆ। ਸਿਰਫ਼ ਲਿਖਤ ਚੁਣੋ।",
    "sector": "ਤੱਟਵਰਤੀ ਖੇਤਰ",
    "autoSector": "ਚੁਣੇ ਹੋਏ ਸਥਾਨ ਤੋਂ",
    "allSectors": "ਸਾਰੇ ਖੇਤਰ",
    "coverageGap": "ਜਾਣਕਾਰੀ ਉਪਲਬਧ ਨਹੀਂ — ਸਲਾਹ ਜਾਰੀ ਹੋਣ ਦੀ ਪੁਸ਼ਟੀ ਨਹੀਂ",
    "authority": "ਅਥਾਰਟੀ",
  }
};
