import { Link } from "react-router-dom";
import {
  FileText,
  ArrowLeft,
  AlertTriangle,
  Compass,
  ShieldAlert,
  Building,
  Mail,
  Phone,
  Radio,
  Scale,
} from "lucide-react";
import { SEO } from "@/components/SEO";
import { OrcaLogo } from "@/components/orca/Logo";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#06182C] text-slate-100 selection:bg-teal-500/30">
      <SEO
        title="Terms of Service & Maritime Advisory Disclaimer | ORCA Marine AI"
        description="Official terms of use, operational guidelines, IMBL safety protocols, and advisory disclaimers for the ORCA Marine AI platform."
      />

      {/* Header */}
      <header className="sticky top-0 z-30 border-b border-slate-800/80 bg-slate-950/80 backdrop-blur-md px-6 py-4">
        <div className="mx-auto flex max-w-5xl items-center justify-between">
          <Link to="/" className="flex items-center gap-2.5">
            <OrcaLogo className="size-8" />
            <div className="flex flex-col">
              <span className="text-base font-bold tracking-tight text-white font-sans">
                ORCA <span className="text-teal-400">MARINE AI</span>
              </span>
              <span className="text-[10px] font-mono uppercase tracking-widest text-slate-400">
                Ocean Intelligence
              </span>
            </div>
          </Link>

          <Link
            to="/"
            className="inline-flex items-center gap-1.5 rounded-lg border border-slate-800 bg-slate-900/60 px-3.5 py-1.5 text-xs font-medium text-slate-300 hover:bg-slate-800 hover:text-white"
          >
            <ArrowLeft className="size-3.5" />
            <span>Return to Home</span>
          </Link>
        </div>
      </header>

      {/* Main Content */}
      <main className="mx-auto max-w-4xl px-4 py-12">
        {/* Title Header */}
        <div className="border-b border-slate-800 pb-8">
          <div className="inline-flex items-center gap-2 rounded-full border border-sky-500/30 bg-sky-950/40 px-3 py-1 text-xs font-mono text-sky-300">
            <Scale className="size-3.5" />
            <span>MARITIME OPERATIONAL AGREEMENT · SIH 2026</span>
          </div>
          <h1 className="mt-4 text-3xl sm:text-4xl font-bold tracking-tight text-white">
            Terms of Service & Operational Disclaimer
          </h1>
          <p className="mt-2 text-sm text-slate-400 font-mono">
            Last Revised: August 31, 2026 | Applicable to all vessel masters, crew, and coastal operators
          </p>
        </div>

        {/* High-Visibility Maritime Advisory Notice */}
        <div className="my-8 rounded-xl border border-amber-500/30 bg-amber-950/20 p-5 text-sm">
          <h2 className="text-base font-semibold text-amber-300 flex items-center gap-2">
            <AlertTriangle className="size-4 text-amber-400" />
            Crucial Maritime Safety Advisory Notice
          </h2>
          <p className="mt-2 text-slate-300 text-xs sm:text-sm leading-relaxed">
            All ocean state forecasts, Potential Fishing Zone (PFZ) locations, sea surface temperature (SST) fronts, and AI voice copilot recommendations generated by ORCA Marine AI are <strong>advisory in nature</strong>. The vessel skipper / master retains sole and ultimate command responsibility for visual watchkeeping, sound signaling, and compliance with the International Regulations for Preventing Collisions at Sea (COLREGs 1972).
          </p>
        </div>

        {/* Terms Sections */}
        <div className="space-y-8 text-sm leading-relaxed text-slate-300">
          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
              <FileText className="size-5 text-teal-400" />
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing, browsing, or utilizing the ORCA Marine AI platform (via web, mobile interface, or voice telemetry), you agree to be bound by these Terms of Service, all applicable laws of the Republic of India, and guidelines issued by the Ministry of Earth Sciences (MoES) and Directorate General of Shipping.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
              <Compass className="size-5 text-teal-400" />
              2. Earth Observation & Satellite Data Latency
            </h2>
            <p>
              Potential Fishing Zone (PFZ) and oceanographic telemetry are synthesized from Earth Observation satellites (including Oceansat-3, MODIS, Sentinel-3, and INSAT-3DR). Cloud coverage, atmospheric interference, and orbit passes may introduce data latency. Vessel operators should verify local visual sea signs (such as bird diving activity, water color transitions, and depth sounders) before deployment of fishing gear.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
              <ShieldAlert className="size-5 text-rose-400" />
              3. International Maritime Boundary Line (IMBL) Geofencing
            </h2>
            <p>
              The platform incorporates dynamic visual and audio alarms alerting vessels approaching sensitive international maritime borders (e.g. India-Sri Lanka, India-Pakistan, India-Bangladesh). 
            </p>
            <p>
              <strong>Notice:</strong> GPS signal degradation or satellite drift may alter reported coordinates. Vessel operators remain strictly accountable under national and international maritime law for inadvertent territorial boundary crossings.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
              <Radio className="size-5 text-teal-400" />
              4. Emergency SOS & Distress Beacon Protocol
            </h2>
            <p>
              Triggering the ORCA Emergency SOS function dispatches your vessel's latest recorded telemetry to Maritime Rescue Coordination Centres (MRCC) via terrestrial/satellite relay. Intentional or negligent transmission of false distress signals is a punishable offence under the Merchant Shipping Act and Indian Penal Code.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
              <Scale className="size-5 text-teal-400" />
              5. Limitation of Liability
            </h2>
            <p>
              To the maximum extent permitted by applicable Indian law, the developer team (Team OrbitX), INCOIS, and partnering government bodies shall not be liable for any vessel loss, equipment damage, loss of catch, or personal injury resulting from reliance on predictive weather forecasts or algorithmic route optimizations.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">
              6. Intellectual Property & Data Attribution
            </h2>
            <p>
              All oceanographic datasets, bathymetric models, algorithmic models, and platform interface designs are the intellectual property of Team OrbitX and the Indian National Centre for Ocean Information Services (INCOIS), MoES.
            </p>
          </section>

          {/* Contact & Grievance Section */}
          <section className="mt-10 rounded-xl border border-slate-800 bg-slate-950/60 p-6">
            <h2 className="text-lg font-bold text-white flex items-center gap-2">
              <Building className="size-5 text-teal-400" />
              7. Maritime Legal & Operational Office
            </h2>
            <div className="mt-4 grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs font-mono">
              <div className="rounded-lg border border-slate-800 bg-slate-900/60 p-4">
                <span className="text-slate-400 block text-[11px]">NATIONAL HEADQUARTERS</span>
                <strong className="text-white block mt-1">ORCA Operations Command</strong>
                <span className="text-slate-300 block mt-1">
                  INCOIS "Ocean Valley", Pragathi Nagar (BO), Nizampet (SO)<br />
                  Hyderabad, Telangana — 500090, India
                </span>
              </div>

              <div className="rounded-lg border border-slate-800 bg-slate-900/60 p-4 space-y-2">
                <div className="flex items-center gap-2">
                  <Mail className="size-4 text-teal-400" />
                  <span>legal@orca-marine.gov.in</span>
                </div>
                <div className="flex items-center gap-2">
                  <Phone className="size-4 text-emerald-400" />
                  <span>+91 (40) 2389-5000 (General)</span>
                </div>
                <div className="flex items-center gap-2">
                  <Phone className="size-4 text-rose-400" />
                  <span>1554 / 1800-425-1881 (Emergency)</span>
                </div>
              </div>
            </div>
          </section>
        </div>

        <div className="mt-10 border-t border-slate-800 pt-6 flex justify-between items-center text-xs text-slate-400">
          <Link to="/privacy" className="text-teal-400 hover:underline">
            Read Privacy Policy →
          </Link>
          <Link to="/" className="text-slate-300 hover:text-white">
            Return to Dashboard
          </Link>
        </div>
      </main>
    </div>
  );
}
