import { fireEvent, render, screen } from '@testing-library/react';
import { expect, it, vi } from 'vitest';
import { I18nProvider } from '@/lib/orca/i18n';
vi.mock('@/services/api', () => ({ broadcastSOS: vi.fn(), updateSOSDetails: vi.fn() }));
import { broadcastSOS, updateSOSDetails } from '@/services/api';
import EmergencySOSModal from '@/components/EmergencySOSModal';
it('records first without vessel details, retries failure and updates the same request', async () => {
 vi.mocked(broadcastSOS).mockRejectedValueOnce(new Error('503')).mockResolvedValueOnce({status:'RECEIVED',sos_id:'qa-sos'});
 vi.mocked(updateSOSDetails).mockResolvedValue({sos_id:'qa-sos'});
 render(<I18nProvider><EmergencySOSModal isOpen onClose={()=>{}} userLocation={{lat:18.7,lon:73.6}} /></I18nProvider>);
 expect(screen.queryByRole('spinbutton')).not.toBeInTheDocument();
 fireEvent.click(screen.getByRole('button',{name:'Send SOS request'}));
 expect(await screen.findByRole('alert')).toBeInTheDocument();
 expect(screen.queryByRole('textbox')).not.toBeInTheDocument();
 fireEvent.click(screen.getByRole('button',{name:'Send SOS request'}));
 expect(await screen.findByRole('textbox')).toBeInTheDocument();
 expect(broadcastSOS).toHaveBeenLastCalledWith({lat:18.7,lon:73.6,emergency_nature:'General Emergency'});
 fireEvent.change(screen.getByRole('textbox'),{target:{value:'Floodwater entering home'}});
 fireEvent.click(screen.getByRole('button',{name:'Save details'}));
 expect(updateSOSDetails).toHaveBeenCalledWith('qa-sos','Floodwater entering home');
});
